"""
scripts/generate_notebook.py

Generates notebooks/Train_IU_XRay_Colab.ipynb
"""

import json
from pathlib import Path

cells = [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "header_cell"
      },
      "source": [
        "# 🫁 DenseNetBioGPT — Explainable VLM for Radiology Report Generation\n",
        "\n",
        "> **Architecture:** TorchXRayVision DenseNet-121 (vision encoder) + 2-layer MLP projector + BioGPT (language decoder, PEFT LoRA)  \n",
        "> **Dataset:** Indiana University Chest X-Ray (IU X-Ray / OpenI) — 100% public, zero credentialing  \n",
        "> **Designed for:** Free-tier Google Colab T4 (16 GB VRAM) with Google Drive checkpointing\n",
        "\n",
        "---\n",
        "## 📋 Notebook Sections\n",
        "| # | Section | Description |\n",
        "|---|---------|-------------|\n",
        "| 1 | **Environment** | GPU check & runtime verification |\n",
        "| 2 | **Drive Mount** | Persistent checkpoint directory |\n",
        "| 3 | **Clone & Install** | Repo clone + pip dependencies |\n",
        "| 4 | **Dataset** | Download & preprocess IU X-Ray |\n",
        "| 5 | **Smoke Test** | Verify model + data pipeline |\n",
        "| 6 | **Training** | Full training with auto-resume |\n",
        "| 7 | **Evaluation** | BLEU/ROUGE/METEOR metrics on test split |\n",
        "| 8 | **Inference Demo** | Generate reports from sample X-rays |\n",
        "| 9 | **Explainability** | Attention heatmap visualization |\n",
        "| 10 | **Push to HF Hub** | Optional model upload |\n",
        "\n",
        "---\n",
        "> 💡 **Pro Tip:** Run cells top-to-bottom on first run. After any Colab disconnection, skip to **Cell 6** and set `RESUME=True` — checkpoints are on Drive."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "cell_01_env_check",
        "cellView": "form"
      },
      "outputs": [],
      "source": [
        "#@title ### ⚙️ Cell 1 — Environment & GPU Verification\n",
        "#@markdown Confirm CUDA is available and check VRAM. **You need a GPU runtime** (`Runtime → Change runtime type → T4 GPU`).\n",
        "\n",
        "import subprocess, sys, os\n",
        "\n",
        "# GPU info\n",
        "result = subprocess.run(['nvidia-smi', '--query-gpu=name,memory.total,driver_version',\n",
        "                         '--format=csv,noheader'], capture_output=True, text=True)\n",
        "if result.returncode == 0:\n",
        "    gpu_name, vram, driver = [x.strip() for x in result.stdout.strip().split(',')]\n",
        "    print(f\"✅ GPU  : {gpu_name}\")\n",
        "    print(f\"✅ VRAM : {vram}\")\n",
        "    print(f\"✅ Driver: {driver}\")\n",
        "else:\n",
        "    print(\"❌ No GPU detected! Go to Runtime → Change runtime type → T4 GPU\")\n",
        "    raise SystemExit(\"GPU required.\")\n",
        "\n",
        "import torch\n",
        "print(f\"\\n🔥 PyTorch : {torch.__version__}\")\n",
        "print(f\"🔥 CUDA    : {torch.version.cuda}\")\n",
        "print(f\"🔥 cuDNN   : {torch.backends.cudnn.version()}\")\n",
        "print(f\"🔥 Python  : {sys.version.split()[0]}\")\n",
        "assert torch.cuda.is_available(), \"CUDA not available!\"\n",
        "print(f\"\\n🚀 VRAM available: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.2f} GB\")\n",
        "\n",
        "# Check Colab environment\n",
        "IN_COLAB = 'google.colab' in str(subprocess.run(['python', '-c', 'import google.colab'],\n",
        "                                                  capture_output=True).stdout)\n",
        "try:\n",
        "    import google.colab\n",
        "    IN_COLAB = True\n",
        "except ImportError:\n",
        "    IN_COLAB = False\n",
        "\n",
        "print(f\"\\n📍 Running in Google Colab: {IN_COLAB}\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "cell_02_drive_mount",
        "cellView": "form"
      },
      "outputs": [],
      "source": [
        "#@title ### 💾 Cell 2 — Google Drive Mount & Checkpoint Directory\n",
        "#@markdown Mount Google Drive for persistent checkpointing across Colab sessions.\n",
        "#@markdown Your training progress is **never lost** after a disconnect.\n",
        "\n",
        "import os\n",
        "\n",
        "try:\n",
        "    from google.colab import drive\n",
        "    drive.mount('/content/drive', force_remount=False)\n",
        "    CHECKPOINT_DIR = '/content/drive/MyDrive/DenseNetBioGPT_checkpoints'\n",
        "    os.makedirs(CHECKPOINT_DIR, exist_ok=True)\n",
        "    print(f\"✅ Google Drive mounted successfully.\")\n",
        "    print(f\"📁 Checkpoint directory: {CHECKPOINT_DIR}\")\n",
        "except Exception as e:\n",
        "    print(f\"⚠️  Drive mount skipped (running locally or Kaggle): {e}\")\n",
        "    CHECKPOINT_DIR = '/content/checkpoints/densenet_biogpt'\n",
        "    os.makedirs(CHECKPOINT_DIR, exist_ok=True)\n",
        "    print(f\"📁 Using local checkpoint directory: {CHECKPOINT_DIR}\")\n",
        "\n",
        "# Check if a prior checkpoint exists (for resume)\n",
        "best_ckpt = os.path.join(CHECKPOINT_DIR, 'best_checkpoint')\n",
        "has_checkpoint = os.path.exists(best_ckpt) and os.path.exists(\n",
        "    os.path.join(best_ckpt, 'training_state.pt')\n",
        ")\n",
        "if has_checkpoint:\n",
        "    import json\n",
        "    state_path = os.path.join(best_ckpt, 'training_state.pt')\n",
        "    import torch\n",
        "    state = torch.load(state_path, map_location='cpu')\n",
        "    print(f\"\\n🔄 Prior checkpoint found!\")\n",
        "    print(f\"   Epoch: {state.get('epoch', '?')} | Step: {state.get('step', '?')} | Best Val Loss: {state.get('best_val_loss', float('inf')):.4f}\")\n",
        "    print(f\"   ✅ You can resume from Cell 6 by setting RESUME=True\")\n",
        "else:\n",
        "    print(\"\\n🆕 No prior checkpoint found. Fresh training run will begin.\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "cell_03_clone_install",
        "cellView": "form"
      },
      "outputs": [],
      "source": [
        "#@title ### 📦 Cell 3 — Clone Repository & Install Dependencies\n",
        "#@markdown Clones the repo from GitHub and installs all required packages.\n",
        "#@markdown Takes ~3 minutes on first run (mainly torchxrayvision + transformers).\n",
        "\n",
        "import os, subprocess, sys\n",
        "\n",
        "REPO_URL = 'https://github.com/Vikhram-S/explainable-vlm-rad-system'\n",
        "REPO_DIR = '/content/explainable-vlm-rad-system'\n",
        "\n",
        "# --- Clone or pull latest ---\n",
        "if os.path.isdir(os.path.join(REPO_DIR, '.git')):\n",
        "    print(\"📂 Repo already cloned. Pulling latest changes...\")\n",
        "    result = subprocess.run(['git', 'pull', 'origin', 'master'], cwd=REPO_DIR,\n",
        "                             capture_output=True, text=True)\n",
        "    print(result.stdout.strip() or \"Already up to date.\")\n",
        "    if result.returncode != 0:\n",
        "        print(f\"⚠️  git pull warning: {result.stderr.strip()}\")\n",
        "else:\n",
        "    print(f\"📥 Cloning {REPO_URL}...\")\n",
        "    result = subprocess.run(['git', 'clone', '--depth=1', REPO_URL, REPO_DIR],\n",
        "                             capture_output=True, text=True)\n",
        "    if result.returncode != 0:\n",
        "        print(f\"❌ Clone failed:\\n{result.stderr}\")\n",
        "        raise RuntimeError(\"git clone failed\")\n",
        "    print(f\"✅ Repository cloned to {REPO_DIR}\")\n",
        "\n",
        "# --- Set working directory ---\n",
        "os.chdir(REPO_DIR)\n",
        "sys.path.insert(0, REPO_DIR)\n",
        "print(f\"📁 Working directory: {os.getcwd()}\")\n",
        "\n",
        "# --- Install dependencies ---\n",
        "print(\"\\n📦 Installing dependencies (this takes ~3 min)...\")\n",
        "\n",
        "# Pin torch to CUDA-compatible version if needed\n",
        "torch_version_check = subprocess.run(\n",
        "    [sys.executable, '-c', 'import torch; print(torch.cuda.is_available())'],\n",
        "    capture_output=True, text=True\n",
        ").stdout.strip()\n",
        "\n",
        "if torch_version_check != 'True':\n",
        "    print(\"⚠️  PyTorch CUDA not available. Installing CUDA-enabled torch...\")\n",
        "    subprocess.run([\n",
        "        sys.executable, '-m', 'pip', 'install', '-q',\n",
        "        'torch>=2.0.0', 'torchvision>=0.15.0', '--index-url',\n",
        "        'https://download.pytorch.org/whl/cu118'\n",
        "    ], check=True)\n",
        "\n",
        "# Install repo requirements\n",
        "subprocess.run([\n",
        "    sys.executable, '-m', 'pip', 'install', '-q', '-r', 'requirements.txt'\n",
        "], check=True)\n",
        "\n",
        "# Ensure nltk data\n",
        "import nltk\n",
        "for resource in ['wordnet', 'omw-1.4', 'punkt']:\n",
        "    nltk.download(resource, quiet=True)\n",
        "\n",
        "print(\"\\n✅ All dependencies installed successfully!\")\n",
        "\n",
        "# Verify key imports\n",
        "import importlib\n",
        "critical_pkgs = ['torch', 'torchxrayvision', 'transformers', 'peft', 'sacrebleu', 'rouge_score']\n",
        "for pkg in critical_pkgs:\n",
        "    try:\n",
        "        mod = importlib.import_module(pkg.replace('-', '_'))\n",
        "        ver = getattr(mod, '__version__', 'unknown')\n",
        "        print(f\"  ✅ {pkg} == {ver}\")\n",
        "    except ImportError as e:\n",
        "        print(f\"  ❌ {pkg} FAILED: {e}\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "cell_04_dataset",
        "cellView": "form"
      },
      "outputs": [],
      "source": [
        "#@title ### 📊 Cell 4 — Download & Preprocess IU X-Ray (OpenI) Dataset\n",
        "#@markdown Downloads the official NLM OpenI IU X-Ray dataset (~380 MB reports + ~1.3 GB images).\n",
        "#@markdown Parses XML reports, filters empty/trivial findings, and creates patient-level 70/10/20 splits.\n",
        "#@markdown ⚠️ **No MIMIC-CXR or credentialed data is used.** This dataset is fully open-access.\n",
        "\n",
        "import os, subprocess, sys, json\n",
        "\n",
        "DATA_DIR = 'data/iu_xray'\n",
        "SPLITS_DIR = os.path.join(DATA_DIR, 'splits')\n",
        "\n",
        "# Check if already downloaded\n",
        "if (os.path.exists(os.path.join(SPLITS_DIR, 'train.json')) and\n",
        "    os.path.exists(os.path.join(SPLITS_DIR, 'val.json')) and\n",
        "    os.path.exists(os.path.join(SPLITS_DIR, 'test.json'))):\n",
        "\n",
        "    print(\"✅ Dataset splits already exist. Skipping download.\")\n",
        "    with open(os.path.join(DATA_DIR, 'dataset_summary.json'), 'r') as f:\n",
        "        summary = json.load(f)\n",
        "    print(f\"  Total filtered reports  : {summary.get('total_filtered_reports', '?')}\")\n",
        "    print(f\"  Train / Val / Test split: {summary.get('train_reports','?')} / {summary.get('val_reports','?')} / {summary.get('test_reports','?')}\")\n",
        "    print(f\"  Avg findings words      : {summary.get('avg_findings_words', '?')}\")\n",
        "else:\n",
        "    print(\"📥 Downloading IU X-Ray reports and images from NLM OpenI...\")\n",
        "    print(\"   (Reports ~380 MB + Images ~1.36 GB — allow 5–10 minutes)\")\n",
        "\n",
        "    result = subprocess.run(\n",
        "        [sys.executable, 'scripts/download_and_preprocess_openi.py',\n",
        "         '--output_dir', DATA_DIR, '--download_images'],\n",
        "        capture_output=False,   # show stdout in notebook\n",
        "        text=True\n",
        "    )\n",
        "    if result.returncode != 0:\n",
        "        print(f\"❌ Download script failed!\")\n",
        "        raise RuntimeError(\"Dataset download failed\")\n",
        "\n",
        "    print(\"\\n✅ Dataset download and preprocessing complete!\")\n",
        "\n",
        "# Verify splits\n",
        "for split in ['train', 'val', 'test']:\n",
        "    path = os.path.join(SPLITS_DIR, f'{split}.json')\n",
        "    with open(path, 'r') as f:\n",
        "        records = json.load(f)\n",
        "    print(f\"  {split:5s}: {len(records):4d} studies\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "cell_05_smoke_test",
        "cellView": "form"
      },
      "outputs": [],
      "source": [
        "#@title ### 🧪 Cell 5 — Smoke Test: Model Architecture & Data Pipeline Verification\n",
        "#@markdown Runs all 5 unit tests: dataset collation, forward pass, backward pass,\n",
        "#@markdown gradient freezing verification, and checkpoint round-trip.\n",
        "#@markdown Catches any environment issues before committing GPU hours to training.\n",
        "\n",
        "import subprocess, sys\n",
        "\n",
        "print(\"🔬 Running comprehensive model and dataset verification...\")\n",
        "result = subprocess.run(\n",
        "    [sys.executable, 'tests/test_model_and_dataset.py'],\n",
        "    capture_output=False,\n",
        "    text=True\n",
        ")\n",
        "if result.returncode == 0:\n",
        "    print(\"\\n✅ ALL TESTS PASSED — System is ready for training!\")\n",
        "else:\n",
        "    print(f\"\\n❌ Tests failed. Review output above before proceeding to training.\")\n",
        "    raise RuntimeError(\"Smoke test failed\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "cell_06_training",
        "cellView": "form"
      },
      "outputs": [],
      "source": [
        "#@title ### 🚀 Cell 6 — Training (with Auto-Resume Support)\n",
        "#@markdown Configure hyperparameters and launch training.\n",
        "#@markdown **Auto-resume**: set `RESUME = True` to pick up from the last Drive checkpoint.\n",
        "\n",
        "# ============================================================\n",
        "#  HYPERPARAMETER CONFIGURATION\n",
        "# ============================================================\n",
        "RESUME = False           #@param {type:\"boolean\"}\n",
        "EPOCHS = 10              #@param {type:\"integer\"}\n",
        "BATCH_SIZE = 4           #@param [\"2\", \"4\", \"8\"] {type:\"raw\"}\n",
        "GRAD_ACCUM_STEPS = 4     #@param {type:\"integer\"}\n",
        "LR_PROJECTOR = 2e-4      #@param {type:\"number\"}\n",
        "LR_ENCODER = 2e-5        #@param {type:\"number\"}\n",
        "LORA_R = 16              #@param [\"8\", \"16\", \"32\"] {type:\"raw\"}\n",
        "LORA_ALPHA = 32          #@param {type:\"integer\"}\n",
        "MAX_LENGTH = 128         #@param {type:\"integer\"}\n",
        "SAVE_STEPS = 100         #@param {type:\"integer\"}\n",
        "EVAL_STEPS = 100         #@param {type:\"integer\"}\n",
        "USE_FP16 = True          #@param {type:\"boolean\"}\n",
        "# ============================================================\n",
        "\n",
        "import subprocess, sys, os\n",
        "\n",
        "# Effective batch size\n",
        "eff_bs = BATCH_SIZE * GRAD_ACCUM_STEPS\n",
        "print(f\"{'='*60}\")\n",
        "print(f\"  DenseNetBioGPT Training Configuration\")\n",
        "print(f\"{'='*60}\")\n",
        "print(f\"  Checkpoint dir     : {CHECKPOINT_DIR}\")\n",
        "print(f\"  Resume from ckpt   : {RESUME}\")\n",
        "print(f\"  Epochs             : {EPOCHS}\")\n",
        "print(f\"  Micro-batch size   : {BATCH_SIZE}\")\n",
        "print(f\"  Gradient accum     : {GRAD_ACCUM_STEPS}\")\n",
        "print(f\"  Effective batch sz : {eff_bs}\")\n",
        "print(f\"  LR (projector/LoRA): {LR_PROJECTOR}\")\n",
        "print(f\"  LR (DenseBlock4)   : {LR_ENCODER}\")\n",
        "print(f\"  LoRA rank          : {LORA_R}, alpha: {LORA_ALPHA}\")\n",
        "print(f\"  Mixed precision    : {'fp16' if USE_FP16 else 'fp32'}\")\n",
        "print(f\"  Save every N steps : {SAVE_STEPS}\")\n",
        "print(f\"{'='*60}\")\n",
        "\n",
        "cmd = [\n",
        "    sys.executable, 'scripts/train.py',\n",
        "    '--data_dir', 'data/iu_xray',\n",
        "    '--output_dir', CHECKPOINT_DIR,\n",
        "    '--epochs', str(EPOCHS),\n",
        "    '--batch_size', str(BATCH_SIZE),\n",
        "    '--grad_accum_steps', str(GRAD_ACCUM_STEPS),\n",
        "    '--lr_projector', str(LR_PROJECTOR),\n",
        "    '--lr_encoder', str(LR_ENCODER),\n",
        "    '--lora_r', str(LORA_R),\n",
        "    '--lora_alpha', str(LORA_ALPHA),\n",
        "    '--max_length', str(MAX_LENGTH),\n",
        "    '--save_steps', str(SAVE_STEPS),\n",
        "    '--eval_steps', str(EVAL_STEPS),\n",
        "    '--seed', '42',\n",
        "]\n",
        "\n",
        "if USE_FP16:\n",
        "    cmd.append('--fp16')\n",
        "else:\n",
        "    cmd.append('--no_fp16')\n",
        "\n",
        "if RESUME:\n",
        "    resume_path = os.path.join(CHECKPOINT_DIR, 'best_checkpoint')\n",
        "    if os.path.exists(resume_path):\n",
        "        cmd += ['--resume_from', resume_path]\n",
        "        print(f\"🔄 Resuming from: {resume_path}\")\n",
        "    else:\n",
        "        print(f\"⚠️  Resume path not found: {resume_path}. Starting fresh.\")\n",
        "\n",
        "print(\"\\n🚀 Launching training...\")\n",
        "result = subprocess.run(cmd, capture_output=False, text=True)\n",
        "if result.returncode != 0:\n",
        "    print(\"❌ Training process exited with an error.\")\n",
        "else:\n",
        "    print(\"\\n✅ Training complete!\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "cell_07_evaluation",
        "cellView": "form"
      },
      "outputs": [],
      "source": [
        "#@title ### 📈 Cell 7 — Evaluation on Held-Out Test Split\n",
        "#@markdown Evaluates the best checkpoint on the held-out IU X-Ray test split.\n",
        "#@markdown Computes BLEU-1/2/3/4, ROUGE-1/2/L, METEOR, and Corpus SacreBLEU.\n",
        "#@markdown Results are saved to `results/metrics.json`.\n",
        "\n",
        "import subprocess, sys, json, os\n",
        "\n",
        "os.makedirs('results', exist_ok=True)\n",
        "\n",
        "BEST_CKPT = os.path.join(CHECKPOINT_DIR, 'best_checkpoint')\n",
        "EVAL_BATCH_SIZE = 8  #@param {type:\"integer\"}\n",
        "MAX_SAMPLES = None   #@param {type:\"raw\"} // Set to int (e.g. 50) to quick-eval on subset\n",
        "\n",
        "if not os.path.exists(BEST_CKPT):\n",
        "    print(f\"⚠️  Best checkpoint not found at {BEST_CKPT}\")\n",
        "    print(\"   Run Cell 6 (training) first, or check CHECKPOINT_DIR.\")\n",
        "else:\n",
        "    print(f\"📊 Evaluating checkpoint: {BEST_CKPT}\")\n",
        "\n",
        "    cmd = [\n",
        "        sys.executable, 'scripts/eval.py',\n",
        "        '--checkpoint_dir', BEST_CKPT,\n",
        "        '--split_file', 'data/iu_xray/splits/test.json',\n",
        "        '--images_dir', 'data/iu_xray/images',\n",
        "        '--output_file', 'results/metrics.json',\n",
        "        '--batch_size', str(EVAL_BATCH_SIZE),\n",
        "    ]\n",
        "    if MAX_SAMPLES is not None:\n",
        "        cmd += ['--max_samples', str(MAX_SAMPLES)]\n",
        "\n",
        "    result = subprocess.run(cmd, capture_output=False, text=True)\n",
        "\n",
        "    if result.returncode == 0 and os.path.exists('results/metrics.json'):\n",
        "        with open('results/metrics.json', 'r') as f:\n",
        "            res = json.load(f)\n",
        "\n",
        "        m = res.get('metrics', {})\n",
        "        print(\"\\n\" + \"=\"*55)\n",
        "        print(f\"  📋 IU X-Ray Test Split Results  (N={m.get('num_evaluated_samples','?')})\")\n",
        "        print(\"=\"*55)\n",
        "        print(f\"  BLEU-1  : {m.get('bleu_1',0):.4f}\")\n",
        "        print(f\"  BLEU-2  : {m.get('bleu_2',0):.4f}\")\n",
        "        print(f\"  BLEU-3  : {m.get('bleu_3',0):.4f}\")\n",
        "        print(f\"  BLEU-4  : {m.get('bleu_4',0):.4f}\")\n",
        "        print(f\"  ROUGE-1 : {m.get('rouge_1',0):.4f}\")\n",
        "        print(f\"  ROUGE-2 : {m.get('rouge_2',0):.4f}\")\n",
        "        print(f\"  ROUGE-L : {m.get('rouge_l',0):.4f}\")\n",
        "        print(f\"  METEOR  : {m.get('meteor',0):.4f}\")\n",
        "        print(f\"  SacreBLEU (corpus): {m.get('sacrebleu',0):.2f}\")\n",
        "        print(\"=\"*55)\n",
        "\n",
        "        # Show 3 sample predictions\n",
        "        samples = res.get('sample_predictions', [])[:3]\n",
        "        if samples:\n",
        "            print(\"\\n📄 Sample Predictions:\")\n",
        "            for i, s in enumerate(samples, 1):\n",
        "                print(f\"\\n  [Study {i}: {s['study_id']}]\")\n",
        "                print(f\"  GT : {s['ground_truth'][:120]}...\")\n",
        "                print(f\"  GEN: {s['generated_prediction'][:120]}...\")\n",
        "    else:\n",
        "        print(\"❌ Evaluation failed. Check output above.\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "cell_08_training_curves",
        "cellView": "form"
      },
      "outputs": [],
      "source": [
        "#@title ### 📉 Cell 8 — Training Loss Curves & Learning Rate Schedule\n",
        "#@markdown Plots validation loss curve and LR schedule from training history.\n",
        "#@markdown Useful for diagnosing convergence, overfitting, or underfitting.\n",
        "\n",
        "import json, os\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.ticker as ticker\n",
        "\n",
        "history_path = os.path.join(CHECKPOINT_DIR, 'best_checkpoint', 'train_history.json')\n",
        "\n",
        "if not os.path.exists(history_path):\n",
        "    # Try final checkpoint\n",
        "    history_path = os.path.join(CHECKPOINT_DIR, 'final_checkpoint', 'train_history.json')\n",
        "\n",
        "if not os.path.exists(history_path):\n",
        "    print(\"⚠️  train_history.json not found. Run training first.\")\n",
        "else:\n",
        "    with open(history_path) as f:\n",
        "        history = json.load(f)\n",
        "\n",
        "    steps = [h['step'] for h in history]\n",
        "    val_losses = [h['val_loss'] for h in history]\n",
        "    epochs = [h['epoch'] for h in history]\n",
        "    times = [h['time'] / 3600 for h in history]  # hours\n",
        "\n",
        "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
        "    fig.suptitle('DenseNetBioGPT Training Diagnostics', fontsize=14, fontweight='bold')\n",
        "\n",
        "    # Validation Loss\n",
        "    axes[0].plot(steps, val_losses, 'o-', color='royalblue', linewidth=2, markersize=5)\n",
        "    best_idx = val_losses.index(min(val_losses))\n",
        "    axes[0].axvline(steps[best_idx], color='red', linestyle='--', alpha=0.7,\n",
        "                    label=f'Best @ step {steps[best_idx]} (loss={min(val_losses):.4f})')\n",
        "    axes[0].scatter([steps[best_idx]], [val_losses[best_idx]], color='red', zorder=5, s=80)\n",
        "    axes[0].set_xlabel('Global Step')\n",
        "    axes[0].set_ylabel('Validation Loss')\n",
        "    axes[0].set_title('Validation Loss Curve')\n",
        "    axes[0].legend()\n",
        "    axes[0].grid(True, alpha=0.3)\n",
        "\n",
        "    # Val loss vs wall-clock time\n",
        "    axes[1].plot(times, val_losses, 's-', color='darkorange', linewidth=2, markersize=5)\n",
        "    axes[1].set_xlabel('Training Time (hours)')\n",
        "    axes[1].set_ylabel('Validation Loss')\n",
        "    axes[1].set_title('Val Loss vs Wall-Clock Time')\n",
        "    axes[1].grid(True, alpha=0.3)\n",
        "\n",
        "    # Annotate epoch boundaries\n",
        "    seen_epochs = set()\n",
        "    for h in history:\n",
        "        if h['epoch'] not in seen_epochs:\n",
        "            axes[0].axvline(h['step'], color='gray', linestyle=':', alpha=0.4)\n",
        "            axes[0].text(h['step'], max(val_losses)*0.98, f\"E{h['epoch']}\",\n",
        "                        fontsize=7, color='gray', ha='center')\n",
        "            seen_epochs.add(h['epoch'])\n",
        "\n",
        "    plt.tight_layout()\n",
        "    plt.savefig('results/training_curves.png', dpi=150, bbox_inches='tight')\n",
        "    plt.show()\n",
        "    print(f\"\\n📉 Best Val Loss: {min(val_losses):.4f} at step {steps[best_idx]}\")\n",
        "    print(f\"💾 Plot saved to results/training_curves.png\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "cell_09_inference",
        "cellView": "form"
      },
      "outputs": [],
      "source": [
        "#@title ### 🔬 Cell 9 — Inference Demo: Generate Reports from Sample X-Rays\n",
        "#@markdown Loads the best trained checkpoint and generates clinical reports\n",
        "#@markdown for a batch of held-out test X-rays. Compares to ground-truth findings.\n",
        "\n",
        "import torch, json, os, sys\n",
        "from PIL import Image\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.gridspec as gridspec\n",
        "import numpy as np\n",
        "\n",
        "sys.path.insert(0, '/content/explainable-vlm-rad-system')\n",
        "os.chdir('/content/explainable-vlm-rad-system')\n",
        "\n",
        "from src.model import DenseNetBioGPT\n",
        "from src.dataset import load_and_preprocess_cxr\n",
        "from transformers import BioGptTokenizer\n",
        "\n",
        "N_SAMPLES = 4     #@param {type:\"integer\"}\n",
        "NUM_BEAMS = 3     #@param {type:\"integer\"}\n",
        "MAX_TOKENS = 128  #@param {type:\"integer\"}\n",
        "\n",
        "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
        "BEST_CKPT = os.path.join(CHECKPOINT_DIR, 'best_checkpoint')\n",
        "\n",
        "print(\"🔧 Loading tokenizer...\")\n",
        "tokenizer = BioGptTokenizer.from_pretrained('microsoft/biogpt')\n",
        "\n",
        "print(\"🔧 Loading model...\")\n",
        "model = DenseNetBioGPT(biogpt_model_name='microsoft/biogpt', load_pretrained_weights=True)\n",
        "if os.path.exists(BEST_CKPT):\n",
        "    model.load_checkpoint(BEST_CKPT, device=str(device))\n",
        "    print(f\"✅ Loaded trained weights from {BEST_CKPT}\")\n",
        "else:\n",
        "    print(\"⚠️  Using pretrained base weights (no fine-tuned checkpoint found).\")\n",
        "model.to(device)\n",
        "model.eval()\n",
        "\n",
        "# Load test records\n",
        "with open('data/iu_xray/splits/test.json') as f:\n",
        "    test_records = json.load(f)[:N_SAMPLES]\n",
        "\n",
        "IMAGES_DIR = 'data/iu_xray/images'\n",
        "\n",
        "fig = plt.figure(figsize=(16, N_SAMPLES * 4))\n",
        "fig.suptitle('DenseNetBioGPT — Inference on IU X-Ray Test Set', fontsize=14, fontweight='bold')\n",
        "\n",
        "for i, rec in enumerate(test_records):\n",
        "    img_fname = rec.get('frontal_image') or (rec.get('images', [None])[0])\n",
        "    img_path = os.path.join(IMAGES_DIR, img_fname) if img_fname else None\n",
        "\n",
        "    pixel_values = load_and_preprocess_cxr(img_path).unsqueeze(0).to(device)\n",
        "\n",
        "    with torch.no_grad():\n",
        "        reports, _ = model.generate(\n",
        "            pixel_values=pixel_values,\n",
        "            tokenizer=tokenizer,\n",
        "            max_new_tokens=MAX_TOKENS,\n",
        "            num_beams=NUM_BEAMS\n",
        "        )\n",
        "\n",
        "    ax_img = fig.add_subplot(N_SAMPLES, 2, 2*i+1)\n",
        "    if img_path and os.path.exists(img_path):\n",
        "        img = Image.open(img_path).convert('L')\n",
        "        ax_img.imshow(img, cmap='gray')\n",
        "    else:\n",
        "        ax_img.text(0.5, 0.5, 'Image\\nnot found', ha='center', va='center',\n",
        "                    fontsize=12, color='gray')\n",
        "        ax_img.set_facecolor('#1a1a1a')\n",
        "    ax_img.axis('off')\n",
        "    ax_img.set_title(f\"Study: {rec['study_id']}\", fontsize=9)\n",
        "\n",
        "    ax_text = fig.add_subplot(N_SAMPLES, 2, 2*i+2)\n",
        "    gt_text = rec.get('findings', '')[:300]\n",
        "    gen_text = reports[0][:300]\n",
        "    display_text = (\n",
        "        f\"GROUND TRUTH:\\n{gt_text}\\n\\n\"\n",
        "        f\"─\" * 40 + \"\\n\\n\"\n",
        "        f\"GENERATED:\\n{gen_text}\"\n",
        "    )\n",
        "    ax_text.text(0.02, 0.95, display_text, transform=ax_text.transAxes,\n",
        "                 fontsize=8, va='top', ha='left', wrap=True,\n",
        "                 fontfamily='monospace',\n",
        "                 bbox=dict(boxstyle='round', facecolor='#f0f4f8', alpha=0.8))\n",
        "    ax_text.axis('off')\n",
        "\n",
        "plt.tight_layout()\n",
        "os.makedirs('results', exist_ok=True)\n",
        "plt.savefig('results/inference_demo.png', dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "print(\"\\n💾 Inference visualization saved to results/inference_demo.png\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "cell_10_explainability",
        "cellView": "form"
      },
      "outputs": [],
      "source": [
        "#@title ### 🔥 Cell 10 — Explainability: Attention Heatmap Visualization\n",
        "#@markdown Generates report AND extracts cross-modal attention weights from the final\n",
        "#@markdown decoder layer, upsampled bicubically to 224×224 overlay on the X-ray.\n",
        "#@markdown This is the core **explainability** feature of the DenseNetBioGPT system.\n",
        "\n",
        "import torch, json, os, sys\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.cm as cm\n",
        "from PIL import Image\n",
        "\n",
        "sys.path.insert(0, '/content/explainable-vlm-rad-system')\n",
        "os.chdir('/content/explainable-vlm-rad-system')\n",
        "\n",
        "from src.model import DenseNetBioGPT\n",
        "from src.dataset import load_and_preprocess_cxr\n",
        "from transformers import BioGptTokenizer\n",
        "\n",
        "STUDY_IDX = 0     #@param {type:\"integer\"}\n",
        "LAYER_IDX = -1    #@param {type:\"integer\"}\n",
        "ALPHA = 0.55      #@param {type:\"slider\", min:0.1, max:0.9, step:0.05}\n",
        "\n",
        "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
        "BEST_CKPT = os.path.join(CHECKPOINT_DIR, 'best_checkpoint')\n",
        "\n",
        "tokenizer = BioGptTokenizer.from_pretrained('microsoft/biogpt')\n",
        "model = DenseNetBioGPT(biogpt_model_name='microsoft/biogpt', load_pretrained_weights=True)\n",
        "if os.path.exists(BEST_CKPT):\n",
        "    model.load_checkpoint(BEST_CKPT, device=str(device))\n",
        "model.to(device)\n",
        "model.eval()\n",
        "\n",
        "with open('data/iu_xray/splits/test.json') as f:\n",
        "    test_records = json.load(f)\n",
        "\n",
        "rec = test_records[STUDY_IDX]\n",
        "img_fname = rec.get('frontal_image') or (rec.get('images', [None])[0])\n",
        "img_path = os.path.join('data/iu_xray/images', img_fname) if img_fname else None\n",
        "\n",
        "pixel_values = load_and_preprocess_cxr(img_path).unsqueeze(0).to(device)\n",
        "\n",
        "print(f\"🔍 Generating report and attention heatmap for study: {rec['study_id']}\")\n",
        "print(f\"   Decoder layer: {LAYER_IDX} (−1 = final layer)\")\n",
        "\n",
        "with torch.no_grad():\n",
        "    reports, attentions = model.generate(\n",
        "        pixel_values=pixel_values,\n",
        "        tokenizer=tokenizer,\n",
        "        max_new_tokens=128,\n",
        "        num_beams=1,\n",
        "        output_attentions=True\n",
        "    )\n",
        "\n",
        "generated_report = reports[0]\n",
        "print(f\"\\n📝 Ground Truth:\\n   {rec.get('findings', 'N/A')}\")\n",
        "print(f\"\\n🤖 Generated  :\\n   {generated_report}\")\n",
        "\n",
        "# Extract heatmap\n",
        "if attentions:\n",
        "    heatmap = model.get_token_saliency_map(pixel_values, attentions, layer_idx=LAYER_IDX)\n",
        "    print(f\"\\n🌡️  Heatmap extracted. Shape: {np.array(heatmap).shape}, Range: [{heatmap.min():.3f}, {heatmap.max():.3f}]\")\n",
        "\n",
        "    # --- Visualization ---\n",
        "    fig, axes = plt.subplots(1, 3, figsize=(16, 5.5))\n",
        "    fig.suptitle(f'Explainability Heatmap — Study: {rec[\"study_id\"]}', fontsize=13, fontweight='bold')\n",
        "\n",
        "    if img_path and os.path.exists(img_path):\n",
        "        cxr = np.array(Image.open(img_path).convert('L').resize((224, 224)))\n",
        "    else:\n",
        "        cxr = np.random.randint(50, 200, (224, 224), dtype=np.uint8)\n",
        "\n",
        "    # Original\n",
        "    axes[0].imshow(cxr, cmap='gray')\n",
        "    axes[0].set_title('Original CXR', fontsize=11)\n",
        "    axes[0].axis('off')\n",
        "\n",
        "    # Heatmap only\n",
        "    im = axes[1].imshow(heatmap, cmap='inferno')\n",
        "    axes[1].set_title(f'Attention Heatmap\\n(Layer {LAYER_IDX})', fontsize=11)\n",
        "    axes[1].axis('off')\n",
        "    fig.colorbar(im, ax=axes[1], fraction=0.046, pad=0.04, label='Attention weight')\n",
        "\n",
        "    # Overlay\n",
        "    axes[2].imshow(cxr, cmap='gray')\n",
        "    overlay = axes[2].imshow(heatmap, cmap='jet', alpha=ALPHA)\n",
        "    axes[2].set_title(f'Overlay (α={ALPHA})', fontsize=11)\n",
        "    axes[2].axis('off')\n",
        "    fig.colorbar(overlay, ax=axes[2], fraction=0.046, pad=0.04, label='Attention (jet)')\n",
        "\n",
        "    # Add text below\n",
        "    gen_short = generated_report[:200] + ('...' if len(generated_report) > 200 else '')\n",
        "    fig.text(0.5, -0.03, f\"Generated: {gen_short}\",\n",
        "             ha='center', fontsize=8, style='italic', color='#333')\n",
        "\n",
        "    plt.tight_layout()\n",
        "    os.makedirs('results', exist_ok=True)\n",
        "    plt.savefig('results/attention_heatmap.png', dpi=180, bbox_inches='tight')\n",
        "    plt.show()\n",
        "    print(\"\\n💾 Heatmap saved to results/attention_heatmap.png\")\n",
        "else:\n",
        "    print(\"\\n⚠️  Attention weights not available. Try with num_beams=1 and output_attentions=True.\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "cell_11_param_count",
        "cellView": "form"
      },
      "outputs": [],
      "source": [
        "#@title ### 📐 Cell 11 — Model Parameter Analysis\n",
        "#@markdown Provides a detailed breakdown of trainable vs frozen parameters\n",
        "#@markdown across each model component (encoder, projector, LoRA adapter).\n",
        "\n",
        "import torch, sys, os\n",
        "\n",
        "sys.path.insert(0, '/content/explainable-vlm-rad-system')\n",
        "os.chdir('/content/explainable-vlm-rad-system')\n",
        "\n",
        "from src.model import DenseNetBioGPT\n",
        "\n",
        "model = DenseNetBioGPT(\n",
        "    biogpt_model_name='microsoft/biogpt',\n",
        "    load_pretrained_weights=True,\n",
        "    use_lora=True,\n",
        "    lora_r=16,\n",
        "    lora_alpha=32\n",
        ")\n",
        "\n",
        "def count_params(module):\n",
        "    total = sum(p.numel() for p in module.parameters())\n",
        "    trainable = sum(p.numel() for p in module.parameters() if p.requires_grad)\n",
        "    return total, trainable\n",
        "\n",
        "enc_total, enc_train = count_params(model.vision_encoder)\n",
        "proj_total, proj_train = count_params(model.vision_projector)\n",
        "dec_total, dec_train = count_params(model.decoder)\n",
        "all_total, all_train = count_params(model)\n",
        "\n",
        "def fmt(n): return f\"{n/1e6:.2f}M\"\n",
        "\n",
        "print(\"═\" * 60)\n",
        "print(\"  DenseNetBioGPT — Parameter Count Summary\")\n",
        "print(\"═\" * 60)\n",
        "print(f\"  {'Component':<30} {'Total':>10} {'Trainable':>12}\")\n",
        "print(\"  \" + \"─\" * 56)\n",
        "print(f\"  {'Vision Encoder (DenseNet-121)':<30} {fmt(enc_total):>10} {fmt(enc_train):>12}\")\n",
        "print(f\"  {'Vision Projector (2-layer MLP)':<30} {fmt(proj_total):>10} {fmt(proj_train):>12}\")\n",
        "print(f\"  {'Language Decoder (BioGPT+LoRA)':<30} {fmt(dec_total):>10} {fmt(dec_train):>12}\")\n",
        "print(\"  \" + \"─\" * 56)\n",
        "print(f\"  {'TOTAL':<30} {fmt(all_total):>10} {fmt(all_train):>12}\")\n",
        "print(f\"  {'Training efficiency':<30} {'':>10} {all_train/all_total*100:>11.1f}%\")\n",
        "print(\"═\" * 60)\n",
        "\n",
        "# VRAM estimate\n",
        "param_bytes = all_train * 2  # fp16\n",
        "grad_bytes = all_train * 2\n",
        "optimizer_bytes = all_train * 8  # AdamW: 2 moments × fp32\n",
        "total_vram_est = (param_bytes + grad_bytes + optimizer_bytes) / 1024**3\n",
        "print(f\"\\n  Estimated VRAM (params+grads+optimizer, fp16): ~{total_vram_est:.1f} GB\")\n",
        "print(f\"  Activation memory (batch=4, seq=128+49):       ~2-3 GB\")\n",
        "print(f\"  Total estimated VRAM usage:                    ~{total_vram_est+2.5:.1f} GB\")\n",
        "print(f\"\\n  ✅ Fits within T4/P100 16 GB with batch_size=4 + grad_accum=4\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "cell_12_push_hub",
        "cellView": "form"
      },
      "outputs": [],
      "source": [
        "#@title ### 🤗 Cell 12 — Push to Hugging Face Hub (Optional)\n",
        "#@markdown Upload trained model weights and evaluation metrics to Hugging Face Hub.\n",
        "#@markdown Set `HF_TOKEN` and `HF_REPO_ID` before running.\n",
        "#@markdown Requires that evaluation (Cell 7) has been completed first.\n",
        "\n",
        "import os, subprocess, sys\n",
        "\n",
        "HF_TOKEN = ''        #@param {type:\"string\"}\n",
        "HF_REPO_ID = 'Vikhram-S/densenet-biogpt-iu-xray'  #@param {type:\"string\"}\n",
        "DRY_RUN = True       #@param {type:\"boolean\"}\n",
        "\n",
        "BEST_CKPT = os.path.join(CHECKPOINT_DIR, 'best_checkpoint')\n",
        "METRICS_PATH = 'results/metrics.json'\n",
        "\n",
        "if not os.path.exists(BEST_CKPT):\n",
        "    print(\"❌ No trained checkpoint found. Run Cell 6 first.\")\n",
        "elif not os.path.exists(METRICS_PATH):\n",
        "    print(\"❌ No metrics.json found. Run Cell 7 (evaluation) first.\")\n",
        "elif not HF_TOKEN and not DRY_RUN:\n",
        "    print(\"❌ HF_TOKEN is required. Get yours at https://huggingface.co/settings/tokens\")\n",
        "else:\n",
        "    cmd = [\n",
        "        sys.executable, 'scripts/push_to_hub.py',\n",
        "        '--checkpoint', BEST_CKPT,\n",
        "        '--metrics', METRICS_PATH,\n",
        "        '--repo_id', HF_REPO_ID,\n",
        "    ]\n",
        "    if HF_TOKEN:\n",
        "        cmd += ['--token', HF_TOKEN]\n",
        "    if DRY_RUN:\n",
        "        cmd.append('--dry-run')\n",
        "        print(\"🔍 Dry-run mode enabled — no files will be pushed.\")\n",
        "\n",
        "    result = subprocess.run(cmd, capture_output=False, text=True)\n",
        "    if result.returncode == 0:\n",
        "        if not DRY_RUN:\n",
        "            print(f\"\\n✅ Model pushed to: https://huggingface.co/{HF_REPO_ID}\")\n",
        "    else:\n",
        "        print(\"❌ Push failed. Check output above.\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "footer_cell"
      },
      "source": [
        "---\n",
        "## 📚 Citation & References\n",
        "\n",
        "If you use this work, please cite:\n",
        "\n",
        "```bibtex\n",
        "@misc{vikhram2026explainablevlm,\n",
        "  title={Explainable VLM for Radiology Report Generation: DenseNetBioGPT on IU X-Ray},\n",
        "  author={Vikhram, S.},\n",
        "  year={2026},\n",
        "  url={https://github.com/Vikhram-S/explainable-vlm-rad-system}\n",
        "}\n",
        "```\n",
        "\n",
        "### Key Dependencies\n",
        "| Library | Purpose | Reference |\n",
        "|---------|---------|----------|\n",
        "| [TorchXRayVision](https://github.com/mlmed/torchxrayvision) | DenseNet-121 CXR encoder | Cohen et al. 2022 |\n",
        "| [BioGPT](https://github.com/microsoft/BioGPT) | Biomedical language model | Luo et al. 2022 |\n",
        "| [PEFT](https://github.com/huggingface/peft) | LoRA fine-tuning | Hu et al. 2022 |\n",
        "| [IU X-Ray](https://openi.nlm.nih.gov/) | Dataset | Demner-Fushman et al. 2015 |\n",
        "\n",
        "---\n",
        "*Generated by DenseNetBioGPT Colab Pipeline — [GitHub Repository](https://github.com/Vikhram-S/explainable-vlm-rad-system)*"
      ]
    }
]

nb = {
    "cells": cells,
    "metadata": {
        "language_info": {"name": "python"},
        "accelerator": "GPU",
        "colab": {
            "gpuType": "T4",
            "provenance": [],
            "toc_visible": True,
            "collapsed_sections": []
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

out_path = Path("notebooks/Train_IU_XRay_Colab.ipynb")
out_path.parent.mkdir(parents=True, exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=2)

print(f"Colab training notebook generated at {out_path}")
