"""
push_to_hub.py — Push final model artifacts and code to Hugging Face Hub.

Run AFTER training completes and results/metrics.json has been generated by eval.py.
Usage:
  python scripts/push_to_hub.py \
      --checkpoint checkpoints/best_checkpoint/ \
      --metrics results/metrics.json \
      --repo_id Vikhram-S/mimic-vit-biogpt \
      --token YOUR_HF_TOKEN

Requirements:
  pip install huggingface_hub
"""

import argparse
import json
import os
import re
import shutil
import sys
import tempfile

from huggingface_hub import HfApi, Repository, upload_folder


def inject_metrics_into_readme(readme_path: str, metrics: dict) -> None:
    """Replace the metrics placeholder in README.md with actual evaluation results."""
    with open(readme_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Build the metrics table
    m = metrics
    table_lines = [
        "### Results (post-training)",
        "",
        "Metrics generated by `scripts/eval.py` on 669 held-out IU X-Ray test studies.",
        "",
        "| Metric | Score |",
        "|--------|-------|",
        f"| BLEU-1 | {m.get('bleu_1', 'N/A'):.4f} |",
        f"| BLEU-2 | {m.get('bleu_2', 'N/A'):.4f} |",
        f"| BLEU-3 | {m.get('bleu_3', 'N/A'):.4f} |",
        f"| BLEU-4 | {m.get('bleu_4', 'N/A'):.4f} |",
        f"| ROUGE-1 (F) | {m.get('rouge1', 'N/A'):.4f} |",
        f"| ROUGE-2 (F) | {m.get('rouge2', 'N/A'):.4f} |",
        f"| ROUGE-L (F) | {m.get('rougeL', 'N/A'):.4f} |",
        f"| METEOR | {m.get('meteor', 'N/A'):.4f} |",
        f"| Corpus BLEU (sacrebleu) | {m.get('sacrebleu', 'N/A'):.2f} |",
        "",
        "_Source: `results/metrics.json` — single deterministic run, seed=42, no cherry-picking._",
    ]
    table_str = "\n".join(table_lines)

    # Replace placeholder section
    placeholder_pattern = re.compile(
        r"### Results \(post-training\)\n.*?(?=\n---|\Z)", re.DOTALL
    )
    new_content = placeholder_pattern.sub(table_str, content)

    if new_content == content:
        print("WARNING: Could not find metrics placeholder in README.md. Metrics NOT injected.")
        print("         Please manually insert `results/metrics.json` values into README.md.")
    else:
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print("  -> README.md updated with real evaluation metrics.")


def main():
    parser = argparse.ArgumentParser(description="Push DenseNetBioGPT to Hugging Face Hub")
    parser.add_argument("--checkpoint", required=True, help="Path to best_checkpoint/ directory")
    parser.add_argument("--metrics", required=True, help="Path to results/metrics.json")
    parser.add_argument("--repo_id", default="Vikhram-S/mimic-vit-biogpt", help="HF repo ID")
    parser.add_argument("--token", default=None, help="HuggingFace API token (or set HF_TOKEN env var)")
    parser.add_argument("--dry-run", action="store_true", help="Validate files without pushing")
    args = parser.parse_args()

    token = args.token or os.environ.get("HF_TOKEN")
    if not token and not args.dry_run:
        print("ERROR: Provide --token or set HF_TOKEN environment variable.")
        sys.exit(1)

    # --- Validate inputs ---
    if not os.path.isdir(args.checkpoint):
        print(f"ERROR: Checkpoint directory not found: {args.checkpoint}")
        sys.exit(1)

    if not os.path.isfile(args.metrics):
        print(f"ERROR: Metrics file not found: {args.metrics}")
        sys.exit(1)

    with open(args.metrics, "r", encoding="utf-8") as f:
        metrics = json.load(f)

    required_keys = ["bleu_1", "bleu_2", "bleu_3", "bleu_4", "rouge1", "rouge2", "rougeL", "meteor"]
    missing = [k for k in required_keys if k not in metrics]
    if missing:
        print(f"ERROR: metrics.json missing required keys: {missing}")
        sys.exit(1)

    print(f"Loaded metrics from {args.metrics}:")
    for k, v in metrics.items():
        print(f"  {k}: {v:.4f}" if isinstance(v, float) else f"  {k}: {v}")

    # --- Inject metrics into README ---
    readme_path = "README.md"
    if not os.path.isfile(readme_path):
        print(f"ERROR: README.md not found in current directory.")
        sys.exit(1)

    inject_metrics_into_readme(readme_path, metrics)

    # Copy metrics into results/ for upload
    os.makedirs("results", exist_ok=True)
    shutil.copy(args.metrics, "results/metrics.json")

    if args.dry_run:
        print("\n[DRY RUN] Files validated. No push performed.")
        print("Checkpoint:", args.checkpoint)
        print("README.md: metrics injected locally.")
        print("results/metrics.json: ready.")
        return

    # --- Push to Hub ---
    api = HfApi(token=token)

    # Create repo if it doesn't exist
    try:
        api.repo_info(repo_id=args.repo_id, repo_type="model")
        print(f"Repo exists: {args.repo_id}")
    except Exception:
        api.create_repo(repo_id=args.repo_id, repo_type="model", private=False)
        print(f"Created repo: {args.repo_id}")

    # Upload code files
    print("\nUploading code and documentation...")
    upload_folder(
        folder_path=".",
        repo_id=args.repo_id,
        repo_type="model",
        token=token,
        ignore_patterns=[
            "data/iu_xray/raw/*",
            "data/iu_xray/images/*",
            "checkpoints/*",
            "__pycache__/*",
            "**/__pycache__/*",
            "*.pyc",
            ".git/*",
            ".env",
        ],
        commit_message="Upload DenseNetBioGPT code, splits, and evaluation metrics (IU X-Ray)",
    )
    print("  -> Code and docs uploaded.")

    # Upload model weights from checkpoint
    print("\nUploading model weights from checkpoint...")
    upload_folder(
        folder_path=args.checkpoint,
        repo_id=args.repo_id,
        repo_type="model",
        token=token,
        path_in_repo="model_weights",
        commit_message="Upload DenseNetBioGPT trained weights (IU X-Ray, LoRA+DenseNet4-FT)",
    )
    print("  -> Model weights uploaded to model_weights/")

    print(f"\n=== PUSH COMPLETE ===")
    print(f"View at: https://huggingface.co/{args.repo_id}")


if __name__ == "__main__":
    main()
